fss: Updating

diff --git a/fss b/fss
--- a/fss
+++ b/fss
@@ -3,7 +3,7 @@ set -ue
 command_exists () {
 	command -v "$@" >/dev/null 2>&1
 }
-DEBUGLEVEL=1
+DEBUGLEVEL="1"
 log(){
 	level="$1"
 	shift
@@ -21,6 +21,44 @@ warn(){
 error(){
 	log 0 "ERROR: $@"
 }
+embed_templates(){
+	cd templates
+	for f in *; do
+		echo "template_$(echo "$f" | tr '.' '_')(){"
+		echo "cat <<DOG"
+		cat "$f"
+		echo "DOG"
+		echo "}"
+	done
+}
+while [ $# -gt 0 ]; do
+	case "$1" in
+		--debug)
+			shift
+			DEBUGLEVEL="2"
+		;;
+		--silent)
+			shift
+			DEBUGLEVEL="0"
+		;;
+		embed)
+			shift
+			embed_templates
+			exit
+		;;
+		concat)
+			shift
+			cat "$0"
+			$0 embed
+			cat "$@"
+			exit
+		;;
+		*)
+			break
+		;;
+	esac
+	shift
+done
 FSSVERSION="0.0.2-2-g939d75c"
 package () {
 	NAME=""
@@ -172,16 +210,8 @@ template --src   \"srcfile\"  \\
 			shift
 		done
 	fi
-	# Check to make sure something set our required variables
-	if [ -f "$SRC" -a ! -z "$SRC" ]; then
-		SRC=$SRC
-	elif [ -f "templates/$SRC" -a ! -z "templates/$SRC" ]; then
-		SRC="templates/$SRC"
-	else
-		echo "template: Missing SRC"
-		echo "$usage"
-		return 1
-	fi
+	# Determine our function name
+	func="template_$(echo "$SRC" | tr '.' '_')"
 	if [ -z "$DIST" ]; then
 		echo "template: Missing DIST"
 		echo "$usage"
@@ -190,10 +220,24 @@ template --src   \"srcfile\"  \\
 	info "template called: '$SRC' '$DIST'"
 	# Actually do the magic
 	(
-		echo "cat <<DOG"
-		cat "$SRC"
-		echo "DOG"
-	) | sh > "$DIST"
+		if ! $func 2>/dev/null; then
+			# Check to make sure something set our required variables
+			if [ -f "$SRC" -a ! -z "$SRC" ]; then
+				SRC=$SRC
+			elif [ -f "templates/$SRC" -a ! -z "templates/$SRC" ]; then
+				SRC="templates/$SRC"
+			else
+				echo "template: Missing SRC"
+				echo "$usage"
+				return 1
+			fi
+			(
+				echo "cat <<DOG"
+				cat "$SRC"
+				echo "DOG"
+			) | sh
+		fi
+	) > "$DIST"
 	# Post creation tasks
 	if [ -n "$MODE" ]; then
 		if command_exists chmod; then
