fss: Added updated version

diff --git a/fss b/fss
--- a/fss
+++ b/fss
@@ -3,10 +3,27 @@ set -ue
 command_exists () {
 	command -v "$@" >/dev/null 2>&1
 }
-DEBUG=1
+DEBUGLEVEL=1
+log(){
+	[ $DEBUGLEVEL -ge $1 ] && echo "==> $2"
+}
+debug(){
+	log 2 "DEBUG: $1"
+}
+info(){
+	log 1 "INFO: $1"
+}
+warn(){
+	log 0 "WARNING: $1"
+}
+error(){
+	log 0 "ERROR: $1"
+}
 package () {
 	NAME=""
 	VERSION=""
+	PACKAGE=""
+	MANAGER=""
 	usage="Error calling packages:
 package \"name\"
          -or-
@@ -16,38 +33,42 @@ package --name     \"name\"         \\
         --apt                     \\
         --yum
 "
+	debug "package(\"$@\")"
 	# Too few args
-	if [ $# -lt 2 ]; then
+	if [ $# -lt 1 ]; then
 		echo "Too few arguments"
 		echo "$usage"
 		return 1
 	# First case
-	elif [ $# = 2 ]; then
-		SRC="$1"
-		DIST="$2"
+	elif [ $# = 1 ]; then
+		if [ -f "$1" ]; then
+			PACKAGE="$1"
+		else
+			NAME="$1"
+		fi
 	# Remaining cases
 	else
 		while [ $# -gt 0 ]; do
 			case "$1" in 
-				--src)
+				--name)
 					shift
-					SRC="$1"
+					NAME="$1"
 				;;
-				--dist)
+				--file)
 					shift
-					DIST="$1"
+					PACKAGE="$1"
 				;;
-				--mode)
+				--version)
 					shift
-					MODE="$1"
+					VERSION="$1"
 				;;
-				--user)
+				--apt)
 					shift
-					CHUSER="$1"
+					MANAGER="apt"
 				;;
-				--group)
+				--yum)
 					shift
-					CHGROUP="$1"
+					MANAGER="yum"
 				;;
 				*)
 					echo "Unknown option: $1"
@@ -59,47 +80,36 @@ package --name     \"name\"         \\
 		done
 	fi
 	# Check to make sure something set our required variables
-	if [ -z "$SRC" ]; then
-		echo "Missing SRC"
+	if [ -z "$NAME" -a -z "$PACKAGE" ]; then
+		error "Missing Package name or file"
 		echo "$usage"
 		return 1
 	fi
-	if [ -z "$DIST" ]; then
-		echo "Missing DIST"
-		echo "$usage"
-		return 1
+	# Figure out our package manager
+	if [ -z "$MANAGER" ]; then
+		if command_exists "apt-get" || command_exists "apt"; then
+			MANAGER="apt"
+		elif command_exists "yum"; then
+			MANAGER="yum"
+		fi
 	fi
 	# Actually do the magic
-	(
-		echo "cat <<DOG"
-		cat "$SRC"
-		echo "DOG"
-	) | sh > "$DIST"
-	# Post creation tasks
-	if [ -n "$MODE" ]; then
-		if command -v chmod >/dev/null; then
-			chmod "$MODE" "$DIST"
-		else
-			echo "No such command chmod"
+	case "$MANAGER" in
+		"apt")
+			if command_exists "apt"; then
+				apt install -y "$NAME"
+			else
+				apt-get install -y "$NAME"
+			fi
+		;;
+		"yum")
+			yum install "$NAME"
+		;;
+		*)
+			error "Unknown package manager $MANAGER"
 			return 1
-		fi
-	fi
-	if [ -n "$CHUSER" ]; then
-		if command -v chown >/dev/null; then
-			chown "$CHUSER" "$DIST"
-		else
-			echo "No such command chown"
-			return 1
-		fi
-	fi
-	if [ -n "$CHGROUP" ]; then
-		if command -v chgrp >/dev/null; then
-			chgrp "$CHGROUP" "$DIST"
-		else
-			echo "No such command chgrp"
-			return 1
-		fi
-	fi
+		;;
+	esac
 }
 template () {
 	SRC=""
@@ -116,6 +126,7 @@ template --src   \"srcfile\"  \\
          --user  root       \\
          --group root
 "
+	debug "template(\"$@\")"
 	# Too few args
 	if [ $# -lt 2 ]; then
 		echo "Too few arguments"
@@ -173,7 +184,7 @@ template --src   \"srcfile\"  \\
 		echo "$usage"
 		return 1
 	fi
-	[ $DEBUG -gt 0 ] && echo "template called: '$SRC' '$DIST'"
+	info "template called: '$SRC' '$DIST'"
 	# Actually do the magic
 	(
 		echo "cat <<DOG"
@@ -205,16 +216,18 @@ template --src   \"srcfile\"  \\
 			return 1
 		fi
 	fi
+	# TODO Determine if we did real work
 }
 trap "run_fss $@" EXIT
 run_fss_file() {
 	if [ ! -f "$1" ]; then
-		echo "$1 not a file"
+		error "$1 not a file"
 		exit 1
 	fi
-	[ $DEBUG -gt 0 ] && echo "==> Running $1"
+	info "Running $1"
 	(
-		cd "${1%/*}"
+		BASE="${1%/*}"
+		[ -s "$BASE" ] && cd "$BASE"
 		. "./${1##*/}"
 	)
 }
@@ -222,8 +235,8 @@ run_fss_directory() {
 	if [ ! -d "$1" ]; then
 		return 1
 	fi
-	[ $DEBUG -gt 0 ] && echo "==> Running all in $1"
-	for s in "$1"/*; do
+	info "Running all in $1"
+	for s in $( ls "$1"/* | sort || ls "$1"/* ); do
 		[ -f "$s" ] && run_fss_file "$s" || :
 	done
 }
@@ -231,7 +244,7 @@ run_fss() {
 	tail -n 1 "$0" | grep -q "^ # FSS Last Line Marker$" || return
 	if [ $# = 0 ]; then
 		if ! run_fss_directory "scripts"; then
-			echo "ERROR: scripts directory missing and no scripts passed via cmdline!" >&2
+			error "scripts directory missing and no scripts passed via cmdline!" >&2
 			exit 1
 		fi
 	else
